SPIRIT, STELLAARD, SLIGRO, BAKKER, COFFEMA, KING, KPN1, KPN2, LEGUIDE, LEVBNS, RIJVERS, T, VERLONING, WVDB, DOPPIO,\
        SCANNED, MAKRO, DEKLOKDRANKEN, SCHMIDTZEEVIS, NEWASPECT, DEJONG_LAAN, ENEXIS, BDO, VODAFONE, INVALID = 'SPIRIT',\
        'STELLAARD','SLIGRO', 'BAKKER', 'COFFEMA', 'KING', 'KPN1', 'KPN2', 'LEGUIDE', 'LEVBNS', 'RIJVERS', 'T', 'VERLONING',\
        'WVDB', 'DOPPIO', 'SCANNED', 'MAKRO', 'DEKLOKDRANKEN', 'Schmidt Zeevis', 'NEWASPECT', 'DEJONG_LAAN', 'ENEXIS',\
        'BDO', 'VODAFONE', 'INVALID'

vendorList = [SPIRIT, STELLAARD, SLIGRO, BAKKER, COFFEMA, KING, KPN1, KPN2, LEGUIDE, LEVBNS, RIJVERS, T, VERLONING,
              WVDB, SCANNED, MAKRO, DEKLOKDRANKEN, SCHMIDTZEEVIS, NEWASPECT, DEJONG_LAAN, ENEXIS, INVALID]
